# Generated by Django 4.2.6 on 2023-10-11 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0002_alter_movieorder_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_remove_movie_user_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='movie_order', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
